FROM ubuntu:22.04
RUN apt-get update && apt-get install -y unzip python3 python3-pip
WORKDIR /app
RUN pip3 install numpy
RUN pip3 install torch --index-url https://download.pytorch.org/whl/cpu
RUN pip3 install grpcio==1.58.0 grpcio-tools==1.58.0 
COPY server.py .
COPY modelserver_pb2.py .
COPY modelserver_pb2_grpc.py .
CMD ["python3", "server.py"]